Repository sonisori/Server, pull requests merged in 2024-11, with the labels that each got.

#25 fix: V1 sql의 social type enum 수정
  src/main/java/site/sonisori/sonisori/common/SocialType.java
  src/main/resources/db/migration/V1__init.sql
Labels: 🐛Fix

#23 feat: OAuth2를 이용한 kakao, naver 소셜로그인 구현
  src/main/java/site/sonisori/sonisori/auth/cookie/CookieUtil.java
  src/main/java/site/sonisori/sonisori/auth/jwt/JwtUtil.java
  src/main/java/site/sonisori/sonisori/auth/jwt/exception/JwtFilter.java
  src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
  src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2SuccessHandler.java
  src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2User.java
  src/main/java/site/sonisori/sonisori/auth/oauth2/dto/KakaoResponse.java
  src/main/java/site/sonisori/sonisori/auth/oauth2/dto/NaverResponse.java
  src/main/java/site/sonisori/sonisori/auth/oauth2/dto/OAuth2Response.java
  src/main/java/site/sonisori/sonisori/auth/oauth2/dto/OAuth2UserDto.java
  src/main/java/site/sonisori/sonisori/common/enums/Difficulty.java
  src/main/java/site/sonisori/sonisori/common/enums/Role.java
  src/main/java/site/sonisori/sonisori/common/enums/SocialType.java
  src/main/java/site/sonisori/sonisori/config/SecurityConfig.java
  src/main/java/site/sonisori/sonisori/entity/SignTopic.java
  src/main/java/site/sonisori/sonisori/entity/User.java
  src/main/java/site/sonisori/sonisori/repository/UserRepository.java
Labels: ✨Feature

#30 feat: 자체 로그인 api 구현
  src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2SuccessHandler.java
  src/main/java/site/sonisori/sonisori/common/constants/ErrorMessage.java
  src/main/java/site/sonisori/sonisori/config/SecurityConfig.java
  src/main/java/site/sonisori/sonisori/controller/UserController.java
  src/main/java/site/sonisori/sonisori/dto/user/LoginRequest.java
  src/main/java/site/sonisori/sonisori/exception/GlobalExceptionHandler.java
  src/main/java/site/sonisori/sonisori/exception/InvalidUserException.java
  src/main/java/site/sonisori/sonisori/repository/UserRepository.java
  src/main/java/site/sonisori/sonisori/service/UserService.java
Labels: ✨Feature

#32 feat: 사용자 인증 상태 조회 API 구현
  src/main/java/site/sonisori/sonisori/auth/CustomUserDetails.java
  src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
  src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2SuccessHandler.java
  src/main/java/site/sonisori/sonisori/config/SecurityConfig.java
  src/main/java/site/sonisori/sonisori/controller/UserController.java
  src/main/java/site/sonisori/sonisori/dto/user/AuthResponse.java
  src/main/java/site/sonisori/sonisori/service/UserService.java
Labels: ✨Feature

#40 feat: 마이페이지 조회, 수정 api 구현
  src/main/java/site/sonisori/sonisori/common/constants/ErrorMessage.java
  src/main/java/site/sonisori/sonisori/controller/UserController.java
  src/main/java/site/sonisori/sonisori/dto/user/UpdateUserNameRequest.java
  src/main/java/site/sonisori/sonisori/dto/user/UserProfileResponse.java
  src/main/java/site/sonisori/sonisori/entity/User.java
  src/main/java/site/sonisori/sonisori/service/UserService.java
Labels: ✨Feature

#42 feat: 회원탈퇴 api 구현
  src/main/java/site/sonisori/sonisori/controller/UserController.java
  src/main/java/site/sonisori/sonisori/service/UserService.java
Labels: ✨Feature

#44 feat: 토큰 재발급 api 구현
  src/main/java/site/sonisori/sonisori/auth/jwt/JwtUtil.java
  src/main/java/site/sonisori/sonisori/controller/UserController.java
Labels: ✨Feature

#47 feat: 퀴즈 결과 제출 및 퀴즈 기록 저장 api 구현
  src/main/java/site/sonisori/sonisori/common/constants/ErrorMessage.java
  src/main/java/site/sonisori/sonisori/controller/QuizHistoryController.java
  src/main/java/site/sonisori/sonisori/dto/quizhistory/QuizHistoryRequest.java
  src/main/java/site/sonisori/sonisori/dto/quizhistory/QuizHistoryResponse.java
  src/main/java/site/sonisori/sonisori/entity/QuizHistory.java
  src/main/java/site/sonisori/sonisori/exception/GlobalExceptionHandler.java
  src/main/java/site/sonisori/sonisori/repository/QuizHistoryRepository.java
  src/main/java/site/sonisori/sonisori/service/QuizHistoryService.java
Labels: ✨Feature

#48 chore: CI 파이프라인에 Docker 이미지 빌드 추가
  .github/workflows/ci.yml
  Dockerfile
  docker-compose.yml
Labels: 🧹Chore

#52 chore: ARM 플랫폼 지원을 위한 Docker Buildx 설정 추가
  .github/workflows/ci.yml
Labels: 🧹Chore

#46 feat: 관리자 토픽 추가 api구현
  src/main/java/site/sonisori/sonisori/auth/jwt/JwtUtil.java
  src/main/java/site/sonisori/sonisori/common/constants/ErrorMessage.java
  src/main/java/site/sonisori/sonisori/common/response/SuccessResponse.java
  src/main/java/site/sonisori/sonisori/config/ExceptionHandlerConfig.java
  src/main/java/site/sonisori/sonisori/config/SecurityConfig.java
  src/main/java/site/sonisori/sonisori/controller/SignTopicController.java
  src/main/java/site/sonisori/sonisori/dto/signtopic/SignTopicRequest.java
  src/main/java/site/sonisori/sonisori/service/SignTopicService.java
Labels: ✨Feature

#54 feat: 관리자 토픽삭제기능 구현
  src/main/java/site/sonisori/sonisori/controller/SignTopicController.java
  src/main/java/site/sonisori/sonisori/service/SignTopicService.java
Labels: ✨Feature
