Repository sonisori/Server, pull requests merged in 2024-10, with the labels that each got.

#4 chore: Naver Checkstyle 설정 추가 및 적용
  .editorconfig
  build.gradle
  config/configuration_1_3.dtd
  config/naver-checkstyle-rules.xml
  config/naver-checkstyle-suppressions.xml
  config/naver-intellij-formatter.xml
  config/suppressions_1_1.dtd
Labels: 🧹Chore

#5 chore: Docker Compose를 이용한 MySQL, Redis 및 Flyway 마이그레이션 구현
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/site/sonisori/sonisori/config/FlywayConfig.java
  src/main/resources/db/migration/V1__init.sql
Labels: 🧹Chore

#8 chore: github action을 이용한 CI 파이프라인 구축
  .github/workflows/ci.yml
  build.gradle
Labels: 🧹Chore

#7 feat: 엔티티 구현
  build.gradle
  src/main/java/site/sonisori/sonisori/common/DateEntity.java
  src/main/java/site/sonisori/sonisori/common/Difficulty.java
  src/main/java/site/sonisori/sonisori/common/Role.java
  src/main/java/site/sonisori/sonisori/common/SocialType.java
  src/main/java/site/sonisori/sonisori/entity/QuizHistory.java
  src/main/java/site/sonisori/sonisori/entity/SignQuiz.java
  src/main/java/site/sonisori/sonisori/entity/SignTopic.java
  src/main/java/site/sonisori/sonisori/entity/SignWord.java
  src/main/java/site/sonisori/sonisori/entity/User.java
Labels: ✨Feature

#10 fix: CI Test 오류 해결
  src/main/java/site/sonisori/sonisori/SonisoriApplication.java
  src/main/java/site/sonisori/sonisori/entity/SignTopic.java
  src/test/java/site/sonisori/sonisori/SonisoriApplicationTests.java
Labels: 🐛Fix

#13 chore: Redis 기반 RefreshToken 엔티티 및 Repository 추가
  src/main/java/site/sonisori/sonisori/auth/jwt/entity/RefreshToken.java
  src/main/java/site/sonisori/sonisori/auth/jwt/repository/RefreshTokenRepository.java
Labels: 🧹Chore

#15 feat: global error 처리 및 사용자 정의 error response 추가
  src/main/java/site/sonisori/sonisori/common/constants/ErrorMessage.java
  src/main/java/site/sonisori/sonisori/common/response/ErrorResponse.java
  src/main/java/site/sonisori/sonisori/exception/GlobalExceptionHandler.java
Labels: ✨Feature

#17 feat: slf4j 로그 설정 추가 및 적용
  src/main/java/site/sonisori/sonisori/exception/GlobalExceptionHandler.java
  src/main/resources/logback-spring.xml
Labels: ✨Feature

#20 feat: JWT 인증 및 시큐리티 설정 추가
  build.gradle
  src/main/java/site/sonisori/sonisori/auth/cookie/CookieUtil.java
  src/main/java/site/sonisori/sonisori/auth/jwt/JwtUtil.java
  src/main/java/site/sonisori/sonisori/auth/jwt/dto/TokenDto.java
  src/main/java/site/sonisori/sonisori/auth/jwt/exception/JwtExceptionFilter.java
  src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2User.java
  src/main/java/site/sonisori/sonisori/auth/oauth2/dto/OAuth2UserDto.java
  src/main/java/site/sonisori/sonisori/common/constants/ErrorMessage.java
  src/main/java/site/sonisori/sonisori/config/ExceptionHandlerConfig.java
  src/main/java/site/sonisori/sonisori/config/SecurityConfig.java
  src/main/java/site/sonisori/sonisori/repository/UserRepository.java
Labels: ✨Feature
