Repository sonisori/Server, pull requests merged in 2024-12, with the labels that each got.

#58 feat: 관리자 토픽 수정기능 구현
  src/main/java/site/sonisori/sonisori/controller/SignTopicController.java
  src/main/java/site/sonisori/sonisori/entity/SignTopic.java
  src/main/java/site/sonisori/sonisori/service/SignTopicService.java
Labels: ✨Feature

#60 feat: 관리자 퀴즈 추가 기능 구현
  src/main/java/site/sonisori/sonisori/controller/SignQuizController.java
  src/main/java/site/sonisori/sonisori/dto/signquiz/SignQuizRequest.java
  src/main/java/site/sonisori/sonisori/entity/SignTopic.java
  src/main/java/site/sonisori/sonisori/service/SignQuizService.java
  src/main/java/site/sonisori/sonisori/service/SignTopicService.java
  src/main/java/site/sonisori/sonisori/service/UserService.java
Labels: ✨Feature

#62 feat: 관리자 퀴즈 삭제기능 구현
  src/main/java/site/sonisori/sonisori/common/constants/ErrorMessage.java
  src/main/java/site/sonisori/sonisori/controller/SignQuizController.java
  src/main/java/site/sonisori/sonisori/entity/SignTopic.java
  src/main/java/site/sonisori/sonisori/service/SignQuizService.java
Labels: ✨Feature

#63 chore: github action을 통한 elastic beanstalk CD 설정 추가
  .dockerignore
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  Dokerrun.aws.json
  build.gradle
Labels: 🧹Chore

#65 chore: elastic beanstalk 환경설정에 version label 추가
  .github/workflows/cd.yml
Labels: 🧹Chore

#68 Fix: Elastic Beanstalk 환경 상태가 Ready가 아닌 경우 배포가 실패하는 문제 수정
  .github/workflows/cd.yml
Labels: 🐛Fix

#69 feat: 관리자 퀴즈 수정기능 구현
  src/main/java/site/sonisori/sonisori/controller/SignQuizController.java
  src/main/java/site/sonisori/sonisori/entity/SignQuiz.java
  src/main/java/site/sonisori/sonisori/service/SignQuizService.java
Labels: ✨Feature

#72 chore: cd 파이프라인 수정
  .github/workflows/cd.yml
  Dockerrun.aws.json
Labels: 🧹Chore

#73 feat: 수어 사전 단어 리스트 조회 api 구현
  src/main/java/site/sonisori/sonisori/common/enums/ResourceType.java
  src/main/java/site/sonisori/sonisori/controller/SignWordController.java
  src/main/java/site/sonisori/sonisori/dto/signword/SignWordResponse.java
  src/main/java/site/sonisori/sonisori/entity/SignWord.java
  src/main/java/site/sonisori/sonisori/entity/SignWordResource.java
  src/main/java/site/sonisori/sonisori/repository/SignWordRepository.java
  src/main/java/site/sonisori/sonisori/service/SignWordService.java
  src/main/resources/db/migration/V4__modify_sign_word_table.sql
Labels: ✨Feature

#76 feat: 수어 사전 단어 추가 api 구현
  src/main/java/site/sonisori/sonisori/controller/SignWordController.java
  src/main/java/site/sonisori/sonisori/dto/signword/SignWordRequest.java
  src/main/java/site/sonisori/sonisori/service/SignWordService.java
Labels: ✨Feature

#79 chore: 배포 도메인 cors 설정 및 쿠키 도메인 추가
  src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2SuccessHandler.java
  src/main/java/site/sonisori/sonisori/config/SecurityConfig.java
  src/main/java/site/sonisori/sonisori/controller/UserController.java
Labels: 🧹Chore

#81 feat: 관리자 단어 삭제기능 구현
  src/main/java/site/sonisori/sonisori/common/constants/ErrorMessage.java
  src/main/java/site/sonisori/sonisori/controller/SignWordController.java
  src/main/java/site/sonisori/sonisori/service/SignWordService.java
Labels: ✨Feature

#83 feat: 단어 개별 조회 api 구현 (+oauth2 경로 추가, cascade 설정 추가)
  src/main/java/site/sonisori/sonisori/config/SecurityConfig.java
  src/main/java/site/sonisori/sonisori/controller/SignWordController.java
  src/main/java/site/sonisori/sonisori/dto/signword/SignWordDetailResponse.java
  src/main/java/site/sonisori/sonisori/dto/signwordresource/SignWordResourceDto.java
  src/main/java/site/sonisori/sonisori/dto/signwordresource/SignWordResourceListRequest.java
  src/main/java/site/sonisori/sonisori/entity/SignWord.java
  src/main/java/site/sonisori/sonisori/service/SignWordService.java
  src/main/resources/db/migration/V5__add_cascade_settings.sql
Labels: ✨Feature

#85 feat: 관리자 단어 수정기능 구현
  src/main/java/site/sonisori/sonisori/controller/SignWordController.java
  src/main/java/site/sonisori/sonisori/entity/SignWord.java
  src/main/java/site/sonisori/sonisori/service/SignWordService.java
Labels: ✨Feature

#87 fix: 토큰 재발급 버그 수정
  src/main/java/site/sonisori/sonisori/config/SecurityConfig.java
Labels: 🐛Fix
